"""Genera ``docker-compose.local.yml`` desde ``docker-compose.base.yml`` + manifests.

PR11 — eliminar conflict de merge cuando 2 Archon agents agregan workers en
paralelo:

- Pre-PR11: cada worker nuevo = service hardcoded en ``docker-compose.local.yml``
  → conflict en 1 archivo compartido por cada PR paralelo.
- Post-PR11: cada worker se declara en ``agent.workers[].compose`` del manifest
  del plugin. Este script lee los manifests + el base.yml de infra fija
  (db/temporal/litellm/api/frontend) y compone el yml final.

Workflow:
    1. Editar `plugin.yaml` (agregar/modificar workers) — un solo archivo per-plugin.
    2. `uv run python scripts/render-compose.py`.
    3. Git diff muestra los services nuevos. Commit.
    4. `docker compose -f docker-compose.local.yml up -d`.

Validación (un test en `tests/plugins/test_premortem_invariants.py` verifica que
el `docker-compose.local.yml` commiteado coincide con el output del script —
si están out-of-sync, fail con mensaje "run render-compose.py").

Naming convention: cada worker queda como service
``hubara-worker-<plugin_id>-<worker_name>``. Excepción: si el plugin declara
``compose.service_name: <override>``, gana esa. Útil para preservar nombres
históricos (e.g. el viejo `hubara-worker` para sales).
"""
from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

import yaml


_HUBARA_ROOT = Path(__file__).resolve().parents[1]
_REPO_ROOT = _HUBARA_ROOT.parent
_BASE_YML = _HUBARA_ROOT / "docker-compose.base.yml"
_OUT_YML = _HUBARA_ROOT / "docker-compose.local.yml"
_PLUGINS_DIR = _REPO_ROOT / "frontend_dashboard" / "src" / "plugins"

# Header del archivo generado — usado también por el test de sincronía para
# detectar drift.
_GENERATED_HEADER = (
    "# AUTO-GENERATED by scripts/render-compose.py — DO NOT EDIT.\n"
    "# Edit `docker-compose.base.yml` (infra fija) or `plugin.yaml` (workers)\n"
    "# instead, then re-run: `uv run python scripts/render-compose.py`.\n\n"
)


def _discover_worker_services() -> dict[str, dict[str, Any]]:
    """{service_name: service_spec} para cada worker en los manifests."""
    services: dict[str, dict[str, Any]] = {}
    if not _PLUGINS_DIR.exists():
        return services
    for plugin_dir in sorted(_PLUGINS_DIR.iterdir()):
        if not plugin_dir.is_dir() or plugin_dir.name.startswith("_"):
            continue
        manifest_path = plugin_dir / "plugin.yaml"
        if not manifest_path.exists():
            continue
        manifest = yaml.safe_load(manifest_path.read_text(encoding="utf-8")) or {}
        agent_cfg = manifest.get("agent") or {}
        for worker in agent_cfg.get("workers") or []:
            name, spec = _render_worker_service(plugin_dir.name, worker)
            if name in services:
                raise RuntimeError(
                    f"service name collision: {name!r} declared by 2 workers. "
                    "Use compose.service_name in the manifest to disambiguate."
                )
            services[name] = spec
    return services


def _render_worker_service(plugin_id: str, worker: dict[str, Any]) -> tuple[str, dict[str, Any]]:
    """Convierte un entry de `agent.workers[]` en un service de docker-compose."""
    worker_name = worker["name"]
    module = worker["module"]
    compose_hints = worker.get("compose") or {}

    # Default: hubara-worker-<plugin_id>-<worker_name>. Override opcional.
    service_name = compose_hints.get("service_name") or f"hubara-worker-{plugin_id}-{worker_name}"

    env_dict = compose_hints.get("env") or {}
    env_list = [f"{k}={v}" for k, v in env_dict.items()]

    depends_on: dict[str, dict[str, str]] = {}
    for dep in compose_hints.get("depends_on") or []:
        depends_on[dep] = {"condition": "service_healthy"}

    spec: dict[str, Any] = {
        "build": {"context": "../", "dockerfile": "Dockerfile"},
        "container_name": f"local-{service_name}",
        "working_dir": "/app/hubara_agency",
        "command": ["python", "-m", module],
    }
    if env_list:
        spec["environment"] = env_list
    if compose_hints.get("volumes"):
        spec["volumes"] = list(compose_hints["volumes"])
    if depends_on:
        spec["depends_on"] = depends_on
    return service_name, spec


def _yaml_dump(data: Any) -> str:
    """`yaml.safe_dump` con polish — top-level volumes con valor null se emiten como `volname:`."""
    body = yaml.safe_dump(data, sort_keys=False, default_flow_style=False, width=1000)
    # docker-compose acepta `myvolume:` (sin value) para volumes default-named;
    # PyYAML emite `myvolume: null` que no es válido. Reemplazo defensivo.
    return body.replace(": null\n", ":\n")


def render() -> str:
    """Devuelve el contenido del docker-compose.local.yml como string."""
    if not _BASE_YML.exists():
        raise FileNotFoundError(f"base yml not found: {_BASE_YML}")
    base = yaml.safe_load(_BASE_YML.read_text(encoding="utf-8")) or {}
    base.setdefault("services", {})
    worker_services = _discover_worker_services()
    base["services"].update(worker_services)
    return _GENERATED_HEADER + _yaml_dump(base)


def main() -> None:
    output = render()
    _OUT_YML.write_text(output, encoding="utf-8")
    worker_count = output.count("python\n  - -m\n") + output.count("- python\n      - -m")
    rel = _OUT_YML.relative_to(_REPO_ROOT)
    print(f"[render-compose] wrote {rel} ({len(output)} bytes)")


if __name__ == "__main__":
    main()
