export type {
  CheckDefinition,
  CheckFamily,
  CheckKind,
  CheckLevel,
  CheckRegistry,
  CheckResult,
  CheckStatus,
  CheckVerdict,
  EpisodeRef,
  EpisodeVerdict,
  FailurePoint,
  Fidelity,
  LegacyScore,
  ScorecardDetail,
  ScorecardList,
  ScorecardRow,
  ScorecardWithResults,
  Trajectory,
  TrajectoryTool,
  TrajectoryTurn,
  VerdictCounts,
} from "./model";
export type {
  FamilyGroup,
  FamilyItem,
  StageBand,
  StripCheck,
  StripChip,
  StripChipKind,
  StripColumn,
  StripEventLaneId,
  StripLaneId,
  StripModel,
  StripPoint,
} from "./lib";
export type { RescoreInput } from "./api";
export { checkLevelSchema, checkVerdictSchema } from "./contracts";
export { scorecardKeys } from "./keys";
export {
  EPISODE_VERDICT_ORDER,
  GAP_THRESHOLD_MS,
  STAGE_ORDER,
  STATUS_ORDER,
  STRIP_LANES,
  buildStripModel,
  checkStatus,
  checkVerdictLabel,
  compareEpisodeVerdict,
  compareStatus,
  episodeLabel,
  episodeVerdictColor,
  episodeVerdictLabel,
  failurePointLabel,
  fidelityLabel,
  formatCompliance,
  formatDuration,
  groupResultsByFamily,
  levelColor,
  levelLabel,
  signalLabel,
  stageColor,
  stageLabel,
  stageRank,
  statusColor,
  statusGlyph,
  statusLabel,
  summarizeArgs,
  triggerLabel,
  truncate,
} from "./lib";
export { useCheckRegistry, useRescoreScorecard, useScorecard, useScorecards } from "./api";
