/**
 * Fixture con la forma REAL de `GET /api/agents/{id}/mba-config` (recortada).
 * Solo para tests: espeja el DTO `MbaConfigDTO` del backend.
 */
const HEADERS = {
  Authorization: "Bearer <META_ACCESS_TOKEN>",
  "X-API-Version": "2.0.0",
  "Content-Type": "application/json",
};
const META = "https://api.facebook.com/{entity_id}";

export const MBA_CONFIG_FIXTURE = {
  agent_id: "sales",
  channel: "whatsapp",
  workspace: "hubara_agency/src/plugins/chats/agent/sales/workspace",
  business_info: {
    business_description: "Nombre: Hubara\nIndustria: marca premium colombiana de velas artesanales",
    payment_method: "Contra entrega: solo compras mayores a $45.000 COP.\nPago anticipado: por Nequi o llave 3229041190.",
    delivery_and_shipping: "Envíos a Bogotá: $12.000 a $15.000 aprox. 1 a 2 días hábiles.",
    return_policy: "Garantía: 48 horas de cobertura para envíos rotos o defectuosos.",
    purchase_info: "",
    contact_info: { email: null, hours_of_operation: "America/Bogota", address: null },
    sources: ["USER.md", "skills/hubara_catalog/SKILL.md"],
  },
  settings: {
    rollout_enabled: false,
    ai_audience: "ALLOWLISTED_ONLY",
    handoff: {
      enabled: true,
      message: "Un colega del equipo te responde en este mismo chat 🤍",
      message_selection: "CUSTOM",
    },
    followup: { enabled: false, followup_interval_in_seconds: 900, message: null },
    never_say_phrases: [
      { phrase: "vos", source: "IDENTITY.md" },
      { phrase: "voy a averiguar", source: "AGENTS.md" },
    ],
  },
  skills: [
    {
      title: "persona-y-tono",
      description: "Aplicar en toda conversación: quién es el asesor.",
      skill: "# Eres el Asesor\n\nEres un experto de ventas.",
      char_count: 18204,
      char_limit: 20000,
      over_limit: false,
      sources: ["IDENTITY.md", "SOUL.md"],
    },
    {
      title: "reglas-operativas",
      description: "Aplicar en cada turno.",
      skill: "# Agent rules",
      char_count: 3942,
      char_limit: 20000,
      over_limit: false,
      sources: ["AGENTS.md"],
    },
    {
      title: "guion-sales-script",
      description: "Núcleo del guion conversacional.",
      skill: "# Guion",
      char_count: 20544,
      char_limit: 20000,
      over_limit: true,
      sources: ["skills/sales_script/SKILL.md", "skills/etapa_cierre/SKILL.md"],
    },
  ],
  faqs: [
    {
      question: "¿Cuánto demora el envío?",
      answer: "Bogotá 1 a 2 días hábiles. Resto del país 2 a 3 días hábiles.",
      source: "skills/sales_script/SKILL.md",
    },
  ],
  connector: {
    name: "hubara-commerce",
    description: "API de Hubara: catálogo, pedidos y estado de envío.",
    base_url: "https://<host-publico>/api/mba",
    auth_type: "API_KEY",
    auth_header: "X-API-Key",
    requires_certificate: false,
    tools: [
      {
        name: "check_order_status",
        description: "Cliente pregunta por su pedido (etapa o pago)",
        method: "GET",
        path: "/tools/check_order_status",
        query_parameters: [],
        body_parameters: [],
        bindings: ["WHATSAPP_PHONE_NUMBER"],
        write: false,
        notes: "Lectura: responde desde la fuente de verdad (Medusa / vault).",
        source: "TOOLS.md",
      },
      {
        name: "register_order",
        description: "Cliente tocó '✅ Confirmar' + datos completos",
        method: "POST",
        path: "/tools/register_order",
        query_parameters: [],
        body_parameters: [],
        bindings: ["WHATSAPP_PHONE_NUMBER"],
        write: true,
        notes: "Escritura: el endpoint debe ser idempotente (fingerprint + pre-check).",
        source: "TOOLS.md",
      },
    ],
  },
  ui_skills: [
    {
      title: "request-shipping-details",
      component_type: "flow",
      status: "enabled",
      instruction: "Variantes completas → pedir datos de envío",
      from_tool: "request_shipping_details",
      source: "TOOLS.md",
      kind: "static",
      note: "",
    },
    {
      title: "present-products",
      component_type: "carousel_quick_reply",
      status: "enabled",
      instruction: "4+ productos (catálogo)",
      from_tool: "present_products",
      source: "TOOLS.md",
      kind: "dynamic",
      note: "Dinámico: títulos, fotos y precios salen del catálogo o del connector. A verificar en F0 (sandbox + allowlist).",
    },
  ],
  tool_treatments: [
    { llm_tool: "check_order_status", when: "Cliente pregunta por su pedido", treatment: "connector_tool", detail: "GET https://<host-publico>/api/mba/tools/check_order_status", endpoint: "/{entity_id}/agent_connectors/{connector_id}/tools" },
    { llm_tool: "request_shipping_details", when: "Variantes completas", treatment: "ui_skill", detail: "UI skill nativa `flow` (estática).", endpoint: "/{entity_id}/agent-ui-skills" },
    { llm_tool: "escalate_to_human", when: "Tabla de triggers", treatment: "connector_tool", detail: "POST https://<host-publico>/api/mba/tools/escalate_to_human", endpoint: "/{entity_id}/agent_connectors/{connector_id}/tools" },
    { llm_tool: "react_to_message", when: "Ack visual rápido", treatment: "unmapped", detail: "Sin componente UI equivalente. A verificar en F0: si una reacción toma el hilo.", endpoint: null },
  ],
  excluded: [
    { source: "TOOLS.md#tool:react_to_message", reason: "Sin componente de UI skill equivalente en MBA; enviarlo desde Hubara podría tomar el hilo." },
  ],
  endpoints: [
    { section: "skills", method: "POST", path: "/{entity_id}/agent_config/skills" },
    { section: "business_info", method: "PUT", path: "/{entity_id}/agent_config/business_info" },
    { section: "faqs", method: "POST", path: "/{entity_id}/agent_config/faq" },
    { section: "settings", method: "PUT", path: "/{entity_id}/agent_config/settings" },
    { section: "connector", method: "POST", path: "/{entity_id}/agent_connectors" },
    { section: "connector_tools", method: "POST", path: "/{entity_id}/agent_connectors/{connector_id}/tools" },
    { section: "ui_skills", method: "POST", path: "/{entity_id}/agent-ui-skills" },
    { section: "allowlist", method: "POST", path: "/{entity_id}/agent_config/allowlist" },
  ],
  requests: [
    {
      step: 1,
      section: "business_info",
      label: "business_info",
      method: "PUT",
      url: `${META}/agent_config/business_info`,
      headers: HEADERS,
      body: {
        business_description: "Nombre: Hubara\nIndustria: marca premium colombiana de velas artesanales",
        payment_method: "Contra entrega: solo compras mayores a $45.000 COP.\nPago anticipado: por Nequi o llave 3229041190.",
        delivery_and_shipping: "Envíos a Bogotá: $12.000 a $15.000 aprox. 1 a 2 días hábiles.",
        return_policy: "Garantía: 48 horas de cobertura para envíos rotos o defectuosos.",
        contact_info: { hours_of_operation: "America/Bogota" },
      },
      notes: "PUT reemplaza TODO el bloque; los campos sin fuente no viajan.",
    },
    {
      step: 2,
      section: "faqs",
      label: "¿Cuánto demora el envío?",
      method: "POST",
      url: `${META}/agent_config/faq`,
      headers: HEADERS,
      body: {
        question: "¿Cuánto demora el envío?",
        answer: "Bogotá 1 a 2 días hábiles. Resto del país 2 a 3 días hábiles.",
      },
      notes: "",
    },
    {
      step: 3,
      section: "skills",
      label: "persona-y-tono",
      method: "POST",
      url: `${META}/agent_config/skills`,
      headers: HEADERS,
      body: {
        title: "persona-y-tono",
        description: "Aplicar en toda conversación: quién es el asesor.",
        skill: "# Eres el Asesor\n\nEres un experto de ventas.",
      },
      notes: "",
    },
    {
      step: 4,
      section: "skills",
      label: "reglas-operativas",
      method: "POST",
      url: `${META}/agent_config/skills`,
      headers: HEADERS,
      body: { title: "reglas-operativas", description: "Aplicar en cada turno.", skill: "# Agent rules" },
      notes: "",
    },
    {
      step: 5,
      section: "skills",
      label: "guion-sales-script",
      method: "POST",
      url: `${META}/agent_config/skills`,
      headers: HEADERS,
      body: { title: "guion-sales-script", description: "Núcleo del guion conversacional.", skill: "# Guion" },
      notes: "Excede el límite de 20,000 caracteres: Meta lo rechaza tal cual.",
    },
    {
      step: 6,
      section: "connector",
      label: "hubara-commerce",
      method: "POST",
      url: `${META}/agent_connectors`,
      headers: HEADERS,
      body: {
        name: "hubara-commerce",
        description: "API de Hubara: catálogo, pedidos y estado de envío.",
        base_url: "https://<host-publico>/api/mba",
        auth_type: "API_KEY",
        auth_config: {
          api_key: {
            headers: [{ field_name: "X-API-Key", value: "<HUBARA_MBA_API_KEY>", prefix: "" }],
            query_params: [],
          },
        },
        requires_certificate: false,
      },
      notes: "La respuesta trae el `id` del connector: es el {connector_id} de las tools.",
    },
    {
      step: 7,
      section: "connector_tools",
      label: "check_order_status",
      method: "POST",
      url: `${META}/agent_connectors/{connector_id}/tools`,
      headers: HEADERS,
      body: {
        name: "check_order_status",
        description: "Cliente pregunta por su pedido (etapa o pago)",
        request_definition: {
          method: "GET",
          path: "/tools/check_order_status",
          path_parameters: {},
          query_parameters: {
            customer_phone: {
              type: "string",
              description: "Teléfono del cliente que escribe (lo inyecta Meta, E.164).",
              required: true,
              binding: { kind: "macro", macro: "WHATSAPP_PHONE_NUMBER" },
            },
          },
          headers: {},
        },
        user_auth_required: false,
      },
      notes: "Lectura: responde desde la fuente de verdad (Medusa / vault).",
    },
    {
      step: 8,
      section: "connector_tools",
      label: "register_order",
      method: "POST",
      url: `${META}/agent_connectors/{connector_id}/tools`,
      headers: HEADERS,
      body: {
        name: "register_order",
        description: "Cliente tocó '✅ Confirmar' + datos completos",
        request_definition: {
          method: "POST",
          path: "/tools/register_order",
          path_parameters: {},
          query_parameters: {},
          headers: {},
          body: {
            content_type: "application/json",
            params: {
              customer_phone: {
                type: "string",
                description: "Teléfono del cliente que escribe (lo inyecta Meta, E.164).",
                required: true,
                binding: { kind: "macro", macro: "WHATSAPP_PHONE_NUMBER" },
              },
            },
            required: ["customer_phone"],
          },
        },
        user_auth_required: false,
      },
      notes: "Escritura: el endpoint debe ser idempotente (fingerprint + pre-check).",
    },
    {
      step: 9,
      section: "ui_skills",
      label: "request-shipping-details",
      method: "POST",
      url: `${META}/agent-ui-skills`,
      headers: HEADERS,
      body: {
        title: "request-shipping-details",
        component_type: "flow",
        status: "enabled",
        instruction: "Variantes completas → pedir datos de envío",
      },
      notes: "",
    },
    {
      step: 10,
      section: "ui_skills",
      label: "present-products",
      method: "POST",
      url: `${META}/agent-ui-skills`,
      headers: HEADERS,
      body: {
        title: "present-products",
        component_type: "carousel_quick_reply",
        status: "enabled",
        instruction: "4+ productos (catálogo)",
      },
      notes: "Dinámico: títulos, fotos y precios salen del catálogo o del connector. A verificar en F0 (sandbox + allowlist).",
    },
    {
      step: 11,
      section: "settings",
      label: "settings",
      method: "PUT",
      url: `${META}/agent_config/settings`,
      headers: HEADERS,
      body: {
        rollout: { enabled: false },
        ai_audience: "ALLOWLISTED_ONLY",
        handoff: {
          enabled: true,
          message_selection: "CUSTOM",
          message: "Un colega del equipo te responde en este mismo chat 🤍",
        },
        followup: { enabled: false },
        never_say_phrases: ["vos", "voy a averiguar"],
      },
      notes: "Va al final: con rollout.enabled=false MBA no responde a nadie hasta que se prenda a mano.",
    },
    {
      step: 12,
      section: "allowlist",
      label: "allowlist",
      method: "POST",
      url: `${META}/agent_config/allowlist`,
      headers: HEADERS,
      body: { consumer_phone_number: "+57XXXXXXXXXX" },
      notes: "Único valor que NO sale del workspace: los teléfonos de prueba de F0 (uno por request, E.164).",
    },
  ],
};
