#!/usr/bin/env bash
#
# dump-pipeline-diagnostics.sh — forensic state dump on pipeline failure/cancel
#
# Invoked from hu-hubara-pipeline.yaml as a predecessor to each cancel-* node.
# Produces $ARTIFACTS_DIR/diagnostic-bundle.yaml with EVERYTHING needed to
# diagnose why the workflow stopped, even if Archon logs are gone.
#
# Why this exists: 2026-05-26 a workflow run cancelled mid-implement and the
# only evidence was a corrupt .edit.log. Took ~30min of forensic work to
# pinpoint the cause. With this dump, future debugging is one `cat` away.
#
# Usage:
#   ARTIFACTS_DIR=/path/to/artifacts \
#   CANCEL_NODE=cancel-on-final-validation-fail \
#   CANCEL_REASON="tests failed in batch X" \
#   bash hubara_agency/.hubara/dump-pipeline-diagnostics.sh
#
# Args are read from environment, not positional, so the workflow can pass
# arbitrary context. Missing values get marked as "unknown" in the bundle.
#
# Output: $ARTIFACTS_DIR/diagnostic-bundle.yaml (and tee'd to stderr).

set -u

ARTIFACTS_DIR="${ARTIFACTS_DIR:-}"
CANCEL_NODE="${CANCEL_NODE:-unknown}"
CANCEL_REASON="${CANCEL_REASON:-unknown}"
HU_ID="${HU_ID:-unknown}"
ISSUE_URL="${ISSUE_URL:-unknown}"
PHASE="${PHASE:-unknown}"

if [ -z "$ARTIFACTS_DIR" ]; then
  echo "ERR: ARTIFACTS_DIR env var not set — cannot persist bundle" >&2
  exit 1
fi

mkdir -p "$ARTIFACTS_DIR"
OUT="$ARTIFACTS_DIR/diagnostic-bundle.yaml"

# Helper: safely capture command output with bounded size + redact obvious secrets
capture() {
  local label="$1"
  shift
  printf '  %s: |\n' "$label"
  "$@" 2>&1 \
    | sed 's/[A-Za-z0-9_+/]\{40,\}=*/[REDACTED-LONG-TOKEN]/g' \
    | sed 's/\(Authorization:\s*Bearer\s*\)\S\+/\1[REDACTED]/g' \
    | head -50 \
    | sed 's/^/    /'
}

# Capture starts here. YAML literal block format — readable, parsable.
{
  echo "# Pipeline Diagnostic Bundle"
  echo "# Generated by hubara_agency/.hubara/dump-pipeline-diagnostics.sh"
  echo ""
  echo "meta:"
  printf '  generated_at: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  printf '  cancel_node: %s\n' "$CANCEL_NODE"
  # Escape backslashes + double-quotes for YAML safety, then wrap in quotes
  reason_safe=$(printf '%s' "$CANCEL_REASON" | sed 's/\\/\\\\/g; s/"/\\"/g')
  printf '  cancel_reason: "%s"\n' "$reason_safe"
  printf '  hu_id: %s\n' "$HU_ID"
  printf '  issue_url: %s\n' "$ISSUE_URL"
  printf '  phase: %s\n' "$PHASE"
  printf '  artifacts_dir: %s\n' "$ARTIFACTS_DIR"
  printf '  cwd: %s\n' "$(pwd)"
  echo ""
  echo "artifacts:"
  capture "tree" find "$ARTIFACTS_DIR" -maxdepth 4 -type f -not -name "diagnostic-bundle.yaml"
  echo ""
  capture "edit_log_tail" tail -20 "$ARTIFACTS_DIR/.edit.log"
  echo ""
  echo "git:"
  capture "current_branch" git -C "$(pwd)" branch --show-current
  capture "status_short" git -C "$(pwd)" status --short
  capture "log_last_5" git -C "$(pwd)" log --oneline -5
  capture "log_diff_main" git -C "$(pwd)" log --oneline origin/main..HEAD
  echo ""
  echo "hubara_state:"
  if [ "$HU_ID" != "unknown" ]; then
    capture "refinement_files"     find "hubara_agency/.hubara/refinements"     -maxdepth 2 -name "*${HU_ID}*"
    capture "plan_files"           find "hubara_agency/.hubara/plans/${HU_ID}"  -maxdepth 3 -type f
    capture "spec_deltas"          find "$ARTIFACTS_DIR/spec-deltas"            -maxdepth 4 -type f
    capture "progress_log_tail"    tail -50 "hubara_agency/.hubara/progress-log/${HU_ID}.md"
  else
    echo "  hu_id_unknown: \"cannot list HU-specific paths\""
  fi
  echo ""
  echo "github_project:"
  if [ "$ISSUE_URL" != "unknown" ] && command -v gh >/dev/null 2>&1; then
    capture "issue_status" sh -c "
      gh project item-list 1 --owner einsteindark-edgm --format json --limit 200 2>/dev/null \
        | python3 -c '
import sys, json, re
raw = sys.stdin.read()
cleaned = re.sub(r\"[\\x00-\\x08\\x0B\\x0C\\x0E-\\x1F]\", \"\", raw)
data = json.loads(cleaned)
url = \"$ISSUE_URL\"
for item in data.get(\"items\", []):
    if (item.get(\"content\") or {}).get(\"url\") == url:
        print(\"status:\", item.get(\"status\"))
        print(\"item_id:\", item.get(\"id\"))
        break
else:
    print(\"issue not found in project\")
' 2>&1
    "
  else
    echo "  skipped: \"no ISSUE_URL or no gh CLI\""
  fi
  echo ""
  echo "task_results:"
  # task-result.yaml files from implementer per-task
  capture "task_results_summary" find "$ARTIFACTS_DIR" -maxdepth 6 -name "task-result.yaml"
  echo ""
  echo "evaluation_premortem_review:"
  for f in premortem.yaml evaluation.yaml code-review-findings.yaml; do
    if [ -f "$ARTIFACTS_DIR/$f" ]; then
      printf '  %s_exists: true\n' "${f%.yaml}"
      capture "${f%.yaml}_tail" tail -30 "$ARTIFACTS_DIR/$f"
    else
      printf '  %s_exists: false\n' "${f%.yaml}"
    fi
  done
} > "$OUT" 2>&1

# Echo a short summary to stderr so Archon's log captures it
{
  echo "════════════════════════════════════════════════"
  echo "📋 Pipeline Diagnostic Bundle Written"
  echo "════════════════════════════════════════════════"
  echo "  File:   $OUT"
  echo "  Cancel: $CANCEL_NODE — $CANCEL_REASON"
  echo "  HU:     $HU_ID"
  echo "  Phase:  $PHASE"
  echo "  Run:    bash hubara_agency/.hubara/dump-pipeline-diagnostics.sh"
  echo "          (set ARTIFACTS_DIR + CANCEL_NODE in env to refresh)"
  echo "════════════════════════════════════════════════"
} >&2

# Also expose a flat stdout line so the workflow can chain on it
echo "DIAGNOSTIC_BUNDLE_WRITTEN: $OUT"
exit 0
