/**
 * plugins-sync — escanea `src/plugins/<id>/plugin.yaml` y genera
 * `src/app/plugin-registry.generated.ts` con los entries habilitados.
 *
 * Filtrado por `process.env.ENABLED_PLUGINS` (csv):
 *   - Si está vacío o unset → cargar TODOS los plugins descubiertos.
 *   - Si está seteado       → cargar solo los listados (intersección con
 *                              los que tienen manifest válido).
 *
 * Convención: el archivo generado se ignora vía `.gitignore`. Lo regenera
 * automáticamente `npm run predev` y `npm run prebuild` (ver `package.json`).
 *
 * Diseño explícito:
 *   - Cero dependencias en runtime de la app — el script solo se ejecuta
 *     en build/dev.
 *   - El registry es un módulo TS importable desde `pages/Dashboard.tsx`
 *     (PR3) y desde cualquier shell que necesite enumerar plugins.
 *   - El `Page` se carga con `lazy(() => import("@plugins/<id>/frontend"))`
 *     para code-splitting; el bundler decide el chunking.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const FRONTEND_ROOT = resolve(__dirname, "..");
const PLUGINS_DIR = join(FRONTEND_ROOT, "src", "plugins");
const OUT_FILE = join(FRONTEND_ROOT, "src", "app", "plugin-registry.generated.ts");

type SidebarEntry = {
  route: string;
  label: string;
  icon?: string;
  badge_query?: string;
};

type SectionEntry = {
  key: string;
  label: string;
  order?: number;
};

type DashboardWidget = {
  id: string;
  position: string;
};

type Manifest = {
  id?: string;
  version?: string;
  display_name?: string;
  frontend?: {
    entry?: string;
    contributes?: {
      sidebar?: SidebarEntry[];
      sections?: SectionEntry[];
      dashboard_widgets?: DashboardWidget[];
    };
  };
};

type RegistryEntry = {
  id: string;
  displayName: string;
  sidebar: SidebarEntry[];
  sections: SectionEntry[];
  dashboardWidgets: DashboardWidget[];
};

function discoverManifests(): Map<string, Manifest> {
  const found = new Map<string, Manifest>();

  if (!existsSync(PLUGINS_DIR)) {
    return found;
  }

  for (const entry of readdirSync(PLUGINS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith("_") || entry.name.startsWith(".")) continue;

    const manifestPath = join(PLUGINS_DIR, entry.name, "plugin.yaml");
    if (!existsSync(manifestPath)) continue;

    const raw = readFileSync(manifestPath, "utf-8");
    const manifest = parse(raw) as Manifest;

    if (!manifest?.id || !manifest?.version) {
      console.warn(`[plugins-sync] skip ${entry.name}: missing id or version`);
      continue;
    }
    if (manifest.id !== entry.name) {
      console.warn(
        `[plugins-sync] skip ${entry.name}: manifest id (${manifest.id}) != directory name`,
      );
      continue;
    }

    found.set(entry.name, manifest);
  }

  return found;
}

function filterEnabled(found: Map<string, Manifest>): Manifest[] {
  const envValue = process.env.ENABLED_PLUGINS?.trim();
  if (!envValue) {
    // Sin filtro → cargar todos (modo dev convenient).
    return [...found.values()].sort((a, b) => a.id!.localeCompare(b.id!));
  }
  const enabled = new Set(envValue.split(",").map((s) => s.trim()).filter(Boolean));
  const out: Manifest[] = [];
  for (const id of [...enabled].sort()) {
    const manifest = found.get(id);
    if (!manifest) {
      console.warn(`[plugins-sync] ENABLED_PLUGINS lists "${id}" but no manifest found`);
      continue;
    }
    out.push(manifest);
  }
  return out;
}

function buildEntry(manifest: Manifest): RegistryEntry {
  const contributes = manifest.frontend?.contributes ?? {};
  return {
    id: manifest.id!,
    displayName: manifest.display_name ?? manifest.id!,
    sidebar: contributes.sidebar ?? [],
    sections: (contributes.sections ?? []).slice().sort((a, b) => (a.order ?? 0) - (b.order ?? 0)),
    dashboardWidgets: contributes.dashboard_widgets ?? [],
  };
}

function renderRegistry(entries: RegistryEntry[]): string {
  // `lazy` solo se importa si hay al menos un entry — el tsconfig tiene
  // `noUnusedLocals: true` y rechazaría un import sin uso. Idem para los
  // tipos de React (los entries los necesitan en el typing del array).
  const headerComment = `/**
 * AUTO-GENERATED by frontend_dashboard/scripts/plugins-sync.ts — DO NOT EDIT.
 * Regenerate: \`npm run plugins:sync\`.
 *
 * Source of truth: \`src/plugins/<id>/plugin.yaml\`.
 * Filter: \`process.env.ENABLED_PLUGINS\` (csv; empty = all).
 *
 * Generated: ${new Date().toISOString()}
 * Plugins: ${entries.length === 0 ? "(none)" : entries.map((e) => e.id).join(", ")}
 */
`;

  const sharedTypes = `
export type SidebarEntry = {
  route: string;
  label: string;
  icon?: string;
  badge_query?: string;
};

export type SectionEntry = {
  key: string;
  label: string;
  order?: number;
};

export type DashboardWidget = {
  id: string;
  position: string;
};
`;

  if (entries.length === 0) {
    // Sin plugins: emitimos un array vacío con tipo opaco. Cero imports de
    // React → no se rompe `noUnusedLocals` y la app puede importar PLUGINS
    // de un proyecto recién creado sin friction.
    return (
      headerComment +
      sharedTypes +
      `
export type PluginEntry = {
  id: string;
  displayName: string;
  sidebar: SidebarEntry[];
  sections: SectionEntry[];
  dashboardWidgets: DashboardWidget[];
  Page: () => null;
};

export const PLUGINS: PluginEntry[] = [];
`
    );
  }

  const importBlock = `import { lazy, type ComponentType, type LazyExoticComponent } from "react";\n`;
  const fullType = `
export type PluginEntry = {
  id: string;
  displayName: string;
  sidebar: SidebarEntry[];
  sections: SectionEntry[];
  dashboardWidgets: DashboardWidget[];
  Page: LazyExoticComponent<ComponentType<Record<string, unknown>>>;
};

export const PLUGINS: PluginEntry[] = [
`;

  const body = entries
    .map((e) => {
      // Importamos el barrel del plugin: `@plugins/<id>/frontend` debe exportar
      // un componente default (la "Page" del plugin) — convención FSD-friendly.
      // Si el plugin no tiene frontend ejecutable todavía, exporta un stub.
      const importExpr = `lazy(() => import("@plugins/${e.id}/frontend"))`;
      return `  {
    id: ${JSON.stringify(e.id)},
    displayName: ${JSON.stringify(e.displayName)},
    sidebar: ${JSON.stringify(e.sidebar)},
    sections: ${JSON.stringify(e.sections)},
    dashboardWidgets: ${JSON.stringify(e.dashboardWidgets)},
    Page: ${importExpr},
  },`;
    })
    .join("\n");

  const footer = `\n];\n`;

  return headerComment + importBlock + sharedTypes + fullType + body + footer;
}

function main() {
  const found = discoverManifests();
  const enabled = filterEnabled(found);
  const entries = enabled.map(buildEntry);

  const outDir = dirname(OUT_FILE);
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  writeFileSync(OUT_FILE, renderRegistry(entries), "utf-8");
  console.log(
    `[plugins-sync] generated ${OUT_FILE.replace(FRONTEND_ROOT + "/", "")} ` +
      `with ${entries.length} plugin(s): ${entries.map((e) => e.id).join(", ") || "(empty)"}`,
  );
}

main();
