apiVersion: v1
kind: PersistentVolume
metadata:
  name: hubara-vault-efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: <TU_EFS_ID_AQUI> # REEMPLAZAR CON TU ID REAL DE EFS (Ej: fs-0123456789abcde)
